version: '3'
services:
  authentication-playground: 
    image: nginx:latest
    container_name: authentication-playground
    volumes:
      - ../content:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/apache2/.htpasswd
    ports:
      - 8080:8080