version: '3'
services:
  authentication-playground: 
    build: 
      context: .
    image: authentication-playground:latest
    container_name: authentication-playground
    volumes:
      -  ../content:/usr/share/nginx/html
    ports:
      - 8080:80